packages:
- .
system-ghc: true
resolver:
  compiler: ghc-9.4.2
require-stack-version: ==2.7.5
extra-deps:
  - haskeline-0.8.2
  - regex-base-0.94.0.2
  - regex-tdfa-1.3.2
  - call-stack-0.4.0
  - HUnit-1.6.2.0
